### PR TITLE
feat(popover): Sample `popover` implementation

### PR DESCRIPTION
**Pull request by DethAriel**
This is how `PopoverDirective` might look like. It goes path 1) described #1157 , which results in some copy-paste from `tooltip` component (especially in examples).

**I am NOT expecting that this PR will be merged** - it's just an example implementation that highlights some problems.

The purpose of this PR is to complement the discussion in #1157

### CODE REVIEW

**Comment by adrianfaciu** [comment]
@valorkin Anything I could help with here ? I need popover similar functionality in a project where I already have ng2-bootstrap, so if possible wold love to get this or something similar merged.

**Comment by GuskiS** [comment]
Any progress on this one?

**Comment by valorkin** [comment]
I am restructuring project and adding more tests, and test env configurations. https://github.com/valor-software/ng2-bootstrap/pull/1223
After it I will be ready to merge and add more components, and avoid any regression

**Comment by valorkin** [comment]
Closing in favour of https://github.com/valor-software/ng2-bootstrap/tree/development/src/popover

Huge thank you for your help!

**Pull request closed without merging**
