### PR TITLE
fix(demo): fix input field width for daterangepicker at locales section 

### LINKED ISSUE #3302: fix(demo datepicker): for width less than 1300px data in output field for daterangepicker is cutted at locales example
### Bug description:
- Open demo example on window with width 1300px or less (for example, at mobile device)
- Go to datepicker demo page
- Scroll down page to Locales example
- Choose any daterange at daterangepicker and look at output
### Expected result:
All demo elements should be fully displayed

datepickersmalloutputissue
### Versions of Angular, and Bootstrap:

Angular: all supported

Bootstrap: all supported

### PR DESCRIPTION
**Pull request by ghost**
fix(datepicker): fix width in daterangerpicker at locates example

fixed closes #3302

### CODE REVIEW

**Review by EvilAlexei — CHANGES_REQUESTED** [review]
1. PR message. Not fix(datepicker) -> fix(demo): fix input field width for daterangepicker at locales section
2. Beware of typos - `locates` should be `locales`
3. Where link to original issue?

**Comment by svetoldo4444ka** [comment]
fixes related [#3302]

**Comment by valorkin** [comment]
@EvilAlexei @YevheniiaMazur reviewed and tested?

**Review by EvilAlexei — APPROVED** [review]

**Comment by EvilAlexei** [comment]
@valorkin reviewed and approved

**Pull request merged**
