### PR TITLE
feat(accordion): add output for isOpen state changes

### LINKED ISSUE #556: accordion events
I want to do things when user switches [accordion-group](https://github.com/valor-software/ng2-bootstrap/blob/master/components/accordion/)s of accordion component. Say, I want to save in application state information about which accordion-group is currently open.

Maybe I missing something in the way angular2 does things, but I think this kind of behavior could be achieved with events. Some kind of event like _isOpenChanged_ for accordion-group seems missing to me.

How can I bind some code to user actions of opening and closing accordion groups? Am I right that events are missing?

### PR DESCRIPTION
**Pull request by steelsojka**
This fixes issue https://github.com/valor-software/ngx-bootstrap/issues/2617 without making any breaking changes. This can solve several issues with accordion open state as well.

Closes #556

### CODE REVIEW

**Comment by IlyaSurmay** [comment]
@steelsojka hey, thanks for PR!
only one note, `isOpenChanges` should be renamed to `isOpenChange`
so you can use two way data binding

**Comment by steelsojka** [comment]
@IlyaSurmay I thought about that, but I thought it would be a breaking change since it would have broken one way bindings. I was thinking you would need to emit on `isOpenChange` instead of modifying the internal state, but you could modify the state and notify without breaking current behavior. I'll make the change.

**Comment by IlyaSurmay** [comment]
Tests are failing :( Please fix them, then we'll merge it.

**Review by valorkin — APPROVED** [review]

**Comment by valorkin** [comment]
@steelsojka thanks for your contribution! ;)

**Comment by psined1** [comment]
Hi, any idea when is this going live?

**Comment by valorkin** [comment]
I am trying to publish small versions each Thursday, will be available as @next version
docs are here http://ngx-bootstrap.surge.sh/#/

**Comment by steelsojka** [comment]
@IlyaSurmay Thanks for fixing these tests and getting this working. I've been busy and wasn't able to get to them. I look forward to seeing this in a release!

**Pull request merged**
