### PR TITLE
Pagination: allow setting of a custom css class on <li>

### PR DESCRIPTION
**Pull request by SylTi**
Make possible `<li class="btn btn-primary">` for example

### CODE REVIEW

**Comment by valorkin** [comment]
need to think about it a sec, 
1. classLi property doesn't describe what it does
2. `class="{{ classLi }} " need to check will it work with`[class]="classLi"`

**Comment by SylTi** [comment]
1. I can change the name to something li;e `setLiClass` if you want (I'm open to suggestions).
2. [class] overwrite all existing class. That's not what we want

**Comment by valorkin** [comment]
1. by meaning it seems to be `pageBtnClass` ? seems to be pretty intuitive name
2. what about `[ngClass]` ?

**Comment by SylTi** [comment]
1. Fine by me I will change it to that and push the new commit.
2. It won't work for  the pager already have : `[ngClass]="{'pull-right': align}"`

**Comment by valorkin** [comment]
what I am afraid of: if `pageBtnClass` will change after disable changed, it can overwrite the whole class

**Comment by SylTi** [comment]
By setting the property to `btn btn-primary' : 

https://postimg.org/image/e5s4zkz2x/

Disable seems to work fine.

**Comment by valorkin** [comment]
yes, now it looks much more readable,
if you are in hurry I can merge and publish it is as @beta now and cover with tests later
or you can cover it with test now

**Comment by SylTi** [comment]
I will try to do the tests this weekend !

**Comment by SylTi** [comment]
Is there no existing test for the pagination ? Can't find the .spec

**Pull request merged**
