### PR TITLE
fix(modal): fix memory leak for TemplateRef modals

### LINKED ISSUE #3178: feat(modal): memory leaks in modals created from TemplateRef
### Bug description or feature request:
If modal is created from TemplateRef with component inside, component never gets destroyed which leads to memory leak

### Plunker/StackBlitz that reproduces the issue:
https://plnkr.co/edit/oHULK5YW54gVaX2arIIZ?p=preview
ngOnDestroy in modal content component is never called

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-beta.9

Angular: 4.3.6

Bootstrap: 3.3.7

### Build system: 
Angular CLI

### PR DESCRIPTION
**Pull request by IlyaSurmay**
fixes #3178

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.

### CODE REVIEW

**Review by valorkin — APPROVED** [review]

**Comment by YevheniiaMazur** [comment]
Tested, looks good

**Comment by andy-barnett** [comment]
When is this likely to make it into master?  I'm encountering this issue on 1.9.3.

**Comment by valorkin** [comment]
It will be availbe in v2 beta.11

**Comment by andy-barnett** [comment]
But not backported into v1?

**Comment by valorkin** [comment]
No

**Comment by johaven** [comment]
is it related to https://github.com/valor-software/ngx-bootstrap/issues/2675 ?

**Comment by valorkin** [comment]
Thanks, it was duplicate

**Pull request merged**
