### PR TITLE
fix(weeks): change calculation of week number

### PR DESCRIPTION
**Pull request by vvpanchenko**
bbhqm0jdr9q2slgkyy3owg

### CODE REVIEW

**Comment by vvpanchenko** [comment]
Updated, resolved issue with the end of the year. first last week number

**Comment by vvpanchenko** [comment]
Will be cleaned up and squashed tomorrow morning

**Comment by vvpanchenko** [comment]
Please, take a look at this behavior: https://stackoverflow.com/questions/32120122/difference-between-week-of-year-and-week-of-year-iso-tokens-moment-js

**Review by valorkin — APPROVED** [review]

**Comment by valorkin** [comment]
@vvpanchenko give it to @SergeyKuryatnick for testing

**Comment by vvpanchenko** [comment]
Already, it was in testing about an hour ago, will ask for updating status

**Review by valorkin — APPROVED** [review]

**Pull request merged**
