### PR TITLE
add uk lang

### PR DESCRIPTION
**Pull request by cander2018**
add uk lang

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

### CODE REVIEW

**Comment by valorkin** [comment]
Can you merge 3 PRs in one? Please

**Comment by ctrl-brk** [comment]
You guys might want to rethink the use of 'UK'. The Sublanguage for Englih (United Kingdom) is en-GB. Unless I'm missing something.

**Comment by valorkin** [comment]
http://www.localeplanet.com/icu/uk-UA/index.html

:)

**Comment by ctrl-brk** [comment]
My bad ))

**Comment by valorkin** [comment]
np :)

**Comment by valorkin** [comment]
no reaction, closing

**Pull request closed without merging**
