### PR TITLE
feat(timepicker): new timepicker implementation

### LINKED ISSUE #173: fix(timepicker): spinner doesn't fire change event
The binding for timepicker spinner works but is there a way to get it to fire a change event?

### LINKED ISSUE #793: Timepicker doesn't initialize with ngModel
Hi,
this is my code :

```
<timepicker [ngModel]="startTime" name="startTime" [hourStep]="1" [minuteStep]="15"
                                [showMeridian]="false"></timepicker>
```

the startTime variable is initialized inside the ngOnInit function with a specific DateTime object :

```
let momentTime = moment(this._event.startDateTime * 1000, 'x');
this.startTime = momentTime.toDate();
```

but the timepicker component never show the value of startTime ! only the the current time :(

Does someone have this problem too ?

### LINKED ISSUE #962: Timepicker spinner click won't trigger change function
Here is my code:

``` html
<div class="operation-time col-sm-6">
    <div class="modal-form-label">Open Time:</div>
    <timepicker [(ngModel)]="selectedStartTime" (change)="startTimeChanged()"></timepicker>
</div>
<div class="operation-time col-sm-6">
    <div class="modal-form-label">Close Time:</div>
   <timepicker [(ngModel)]="selectedEndTime" [min]="minEndTime"></timepicker>
</div>
```

I need to change the minEndTime value when the start time has been changed. When I changed the time from the input, it works perfectly. But when I clicked on the spinner to change the start time, the startTimeChanged() was not called. And then I checked the demo, it seems there is no way to trigger change function while using the spinners. Will there be a workaround or something?

### LINKED ISSUE #1253: Timepicker Doesn't have any validation
There is no validation in timepicker. Is it possible to return an null value if the validation fails?
That would be great.

### LINKED ISSUE #1271: Timepicker's invalidHours/invalidMinutes does not apply to inputs
In timepicker, an invalid value is marked in the surrounding `<td>` elements. However, the input still remains `.ng-valid`.

For example, add a minimum value to a timepicker. Type a value in the hour field that is before the minimum time (do not use the arrow icons). `this.invalidHours` will be set to true and `.has-error` will be applied to the surrounding `<td>`. However, `ngClassValid` will remain true.

Can this be fixed? Thanks.

### LINKED ISSUE #1539: Timepicker without chevron doesn't work with bootstrap v4
First of all, thank you for your great job.

In source code of TimePicker you apply `.hidden` class to chevron row to make them hidden. That css class doesn't exist in bootstrap (anymore?).
Probably you can change code to `*ngIf` instead.

### LINKED ISSUE #1672: TimePicker : [showSpinners]="false" not working
"ng2-bootstrap": "1.3.3",

angular 2.4.8.

showMeridian  is working as expected, however if I try to hide the chevrons by setting showSpinners to false the chevrons are still their.

Although it seems that hidden is actualy added to the chevrons class. 

```
<tr class="text-center hidden" ng-reflect-klass="text-center" ng-reflect-ng-class="[object Object]">
          <td><a class="btn btn-link" ng-reflect-klass="btn btn-link" ng-reflect-ng-class="[object Object]"><span class="glyphicon glyphicon-chevron-up"></span></a></td>
          <td>&nbsp;</td>
          <td><a class="btn btn-link" ng-reflect-klass="btn btn-link" ng-reflect-ng-class="[object Object]"><span class="glyphicon glyphicon-chevron-up"></span></a></td>
          <!--template bindings={
  "ng-reflect-ng-if": "true"
}--><td ng-reflect-ng-class="[object Object]"></td>
        </tr>

```

### LINKED ISSUE #1935: For invalid hour and minutes values the timepicker doesn't update the ngModel [timepicker]
There is no validation for entering values like negative numbers in hours or minues in timepicker, the displayed input has the negative number values, but not the NgModel. Please validate this.

### LINKED ISSUE #1957: Timepicker Seconds Field
- [x] Feature Request

## Current Behavior:
Currently timepicker does not have seconds field.

## expected Behavior
It should have seconds field as well, with `up` `down` arrow.

### LINKED ISSUE #1973: Timepicker does not expose any Output events
I am trying to use the timepicker component.  But it does not expose any explicit Output events for changes like the datepicker. In the examples there is (change) being used but this does not fire when using the arrow buttons. It only fires when the input is directly changed. The only thing that works is ngModelChange which is not what I want, because it fires right away without user interaction. 

Is there a workaround?

### LINKED ISSUE #1981: Timepicker minHour maxHour value ?
Hi, the timepicker min max value doesn't work when i use the timepicker. I want the timepicker with the hours between 08:00 and 21:00 for example..Impossible. Any ideas ?

Thanks !

### LINKED ISSUE #2036: TimePicker is dispatching the event 2 times on ngModelChange
Hi,
TimePicker is dispatching the event 2 times on ngModelChange. Could you please let me know how to avoid this or when this will be fixed?

Thanks

### PR DESCRIPTION
**Pull request by valorkin**
fixes #2036
fixes #1981 ( + min max demo )
fixes #1973 
close #1957 ( + seconds demo )
fixes #1935
fixes #1672
feat #1007 added keyboard and mousewheel support
fixes #962
fixes #793
fixes #173
fixes #1271 added custom validation demo
fixes #1539 bs4
fixes #1253 if input is invalid

todo 
- #1814 Added minuteRoundBeforeStep option to timepicker

### CODE REVIEW

**Comment by valorkin** [comment]
by @artemvfrolov 
issue #2058
`time picker`

checking result:

`questions:`
https://github.com/valor-software/ngx-bootstrap/issues/2036 "ngModelChange exists?"
https://github.com/valor-software/ngx-bootstrap/issues/1973 "(change) working only when the input is directly changed"
https://github.com/valor-software/ngx-bootstrap/issues/1935
https://github.com/valor-software/ngx-bootstrap/issues/1271 "after invalid value, if we click on Chevron, error class not change"
https://github.com/valor-software/ngx-bootstrap/issues/1124
https://github.com/valor-software/ngx-bootstrap/issues/793

`fixed:`
https://github.com/valor-software/ngx-bootstrap/issues/1981
https://github.com/valor-software/ngx-bootstrap/issues/1672
https://github.com/valor-software/ngx-bootstrap/issues/1539
https://github.com/valor-software/ngx-bootstrap/issues/1007

`issue:`
https://github.com/valor-software/ngx-bootstrap/issues/1957 "on seconds field arrows not working, validate not working too"
https://github.com/valor-software/ngx-bootstrap/issues/1253
https://github.com/valor-software/ngx-bootstrap/issues/962
https://github.com/valor-software/ngx-bootstrap/issues/173

"in [meridian] when we change meridian, time in input don't change, and when we incrementing value, it incorrect"

"if we want to  enter input value, value is not set, if we clicking on chevron, we have set default value, after that we trying set value again, value is not set, if we trying set invalid value, value is not set, but if we after that trying set valid value again, value is set."

**Comment by valorkin** [comment]
fixes #2036

**Comment by SergeyKuryatnick** [comment]
`npm start` failed with:
87f26b299c

**Comment by SergeyKuryatnick** [comment]
#1253  - checked
#1981 - checked
#2036 - checked
#1957 - checked
#1007 - checked
#793 -  checked
#1271 - checked 
#1935 - dont know what that issue mean
#1672 - need add to demo
#1973 and #962  and #173 - onChaned not work

#1814 - need to check

**Comment by SergeyKuryatnick** [comment]
Changes works normally - checked

**Pull request merged**
