### PR TITLE
fix(rxjs/operators): use rxjs pipeable operators pattern, remove import path(not used)

### PR DESCRIPTION
**Pull request by heeheehi**
This is guid line for rxjs v6
https://docs.google.com/document/d/12nlLt71VLKb-z3YaSGzUfx6mJbc34nsMXtByPUN35cg/edit#

#3841
#4060 
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by ghost** [comment]
@heeheehi awesome 
ngx-bootstrap/src/dropdown/bs-dropdown.directive.ts

I was getting a typescript error 
so happy you fixed this 
import { filter } from 'rxjs/operators'; 🚀 

let me know if you need any help

**Review by iget-master — APPROVED** [review]

**Comment by iget-master** [comment]
Could someone give some attention here?

**Review by leo6104 — CHANGES_REQUESTED** [review]
Can you update this PR to new release target 'Angular 6.0'? 
In Angular 6 & RxJS 6, they only recommend to use 'rxjs' path for operator usage. (not use 'rxjs/operators')

**Comment by heeheehi** [comment]
@valorkin

**Comment by valorkin** [comment]
This week will be released v3 with rxjs version upgrade

**Review by valorkin — APPROVED** [review]

**Comment by valorkin** [comment]
@heeheehi hey, thanks for PR!
It's merged in ngv6 branch
and will be merged in dev as part of upgrade to rxjs 6 and angular 6

**Pull request merged**
