### PR TITLE
 feat(chronos): add danish language locale

### PR DESCRIPTION
**Pull request by perhp**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.

### CODE REVIEW

**Review by valorkin — CHANGES_REQUESTED** [review]
Looks awesome!
Small thing left: export daLocale in srx/index.ts
Or system.js users will not be able to import it :(

**Comment by perhp** [comment]
`daLocale` is exported from `src/locale.ts` which is exported from `src/index.ts` by `export * from './locale';`.
That should do it? :)

**Comment by valorkin** [comment]
Indeed, I forgot that I ended up with this hack for system.js

**Review by valorkin — APPROVED** [review]

**Comment by YevheniiaMazur** [comment]
Tested, looks good

**Pull request merged**
