### PR TITLE
@angular/forms

### PR DESCRIPTION
**Pull request by erashu212**

### CODE REVIEW

**Comment by erashu212** [comment]
@valorkin @valor-software/ng2-team : This works at local environment . But If I see the travis log some process is missing. I have tried to run the same command what travis is running and it working.

Did I miss anything?

**Comment by Dinistro** [comment]
@erashu212 @valorkin It seems like the travis has problemes. In other PR, we see the same messages. #665 #664

**Comment by erashu212** [comment]
@valorkin : This branch could be merged. What do you say?

**Comment by valorkin** [comment]
Looks great! Let me check locally and merge

**Comment by valorkin** [comment]
@Dinistro I see an issue with `Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-linux-x64.tar.gz` all the time

**Comment by Dinistro** [comment]
This was done in #691

**Pull request closed without merging**
