### PR TITLE
feature(RC5 support): Work in progress

### PR DESCRIPTION
**Pull request by marcalj**
From #838

Things to do:
- [x] Create modules for each component
- [x] Create a global module to load all components at once
- [x] Remove @Component({directives: [...]}) properties and add it to the component's module
- [ ] Apply breaking changes from RC5
  - [ ] Remove ComponentResolver, it's deprecated now
  - [ ] @deprecated DynamicComponentLoader. Use ComponentFactoryResolver and ViewContainerRef directly.
  - [x] Replace @Component.events with @Output decorator
  - [x] Replace @Component.host with decorators
  - [x] Replace @Component.inputs with @Input decorator
- [x] Tests refactoring
- [x] Rewrite demo app
- [x] Update Docs

### CODE REVIEW

**Comment by valorkin** [comment]
Hey, please join slack so you can get help with this
Great job! Thanks in advance :)

**Comment by otelnov** [comment]
@marcalj 
All of the old tests + dropdown was rewritten in https://github.com/valor-software/ng2-bootstrap/tree/feat-rc5 branch you can merge it

Also the biggest part of demo app rc5-ready too.

**Comment by a5hik** [comment]
Would be nice to have this merged and the same available as an npm version.

**Comment by aaronleesmith** [comment]
Keep up the good work, guys. Looking forward to this PR.

**Comment by rpedersen** [comment]
What is the slack channel?

**Comment by devoto13** [comment]
FYI I'm working on the last two items here: https://github.com/devoto13/ng2-bootstrap/commits/development

**Comment by otelnov** [comment]
@devoto13 great! Are you in slack?

**Comment by devoto13** [comment]
@otelnov Nope, can you send me link to the Slack?

**Comment by otelnov** [comment]
@rpedersen @devoto13 
https://www.hamsterpad.com/chat/ng2

**Comment by otelnov** [comment]
@devoto13 anyway, let me know when finish, we need merge it asap.
Thanks in advance!

**Pull request closed without merging**
