### PR TITLE
updated to use angular2 alfa 0.48

### PR DESCRIPTION
**Pull request by appfeel**
onInit --> ngOnInit
onDestroy --> ngOnDestroy
doCheck --> ngDoCheck

### CODE REVIEW

**Comment by valorkin** [comment]
@appfeel I will try to degrade rxjs to 0.11 but doesn't really works https://github.com/angular/angular/issues/5643

**Comment by miqmago** [comment]
Hmm.. I'm not really in on it and angular2 is very new to me, so don't know the implications of this issue.

In fact what I've seen is that typescript is copying the entire ng2-bootstrap folder to the outDir so I had to include the following javascript in my index.html:

``` javascript
         System.config({
            packages: {
                'src': {defaultExtension: 'js'},
                'node_modules': {defaultExtension: 'js'}
            }
        });
        System.paths['ng2-bootstrap/*'] = 'node_modules/ng2-bootstrap/*.js'
        System.import('src/app');
```

This was the only way to make ng2-bootstrap to work with angular2 for me: upgrade angular and change onInit, onDestroy and doCheck... (I was uncapable to make it to work with alpha.44)

**Comment by valorkin** [comment]
use 0.46 ng2

**Comment by valorkin** [comment]
and you can check sample for systemjs here: https://github.com/pkozlowski-opensource/ng2-play/pull/34/files

**Comment by lanocturne** [comment]
Hi Valorkin, can you merge this soon. It's not working with ng2 alfa 48+.

**Comment by miqmago** [comment]
If you are going to merge this branch and the other one (https://github.com/valor-software/ng2-bootstrap/pull/43) just let me know and I can manage to resolve the conflicts.

**Comment by valorkin** [comment]
@miqmago hey, yeap, please solve merge conflict and rebase commits, to have one commit per PR
don't forget to update dependencies in package.json
Thanks in advance :)

**Comment by appfeel** [comment]
@valorkin up to date and dependencies updated too :)
If you need just one commit I will delete this PR and create a new one, just let me know

**Comment by valorkin** [comment]
@appfeel problem with v0.48 is 
this error:

```
Module not found: Error: Cannot resolve module 'rxjs/operators/toPromise' in /home/valorkin/work/open-source/ng2-bootstrap/node_modules/angular2/src/facade
```

I was mentioning before
it can be solved by webpack alias for this particular file

**Comment by valorkin** [comment]
please apply this diff and I will merge

``` diff
diff --git a/tsconfig.json b/tsconfig.json
index 7ffcee5..bc8c9e9 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -1,5 +1,5 @@
 {
-  "version": "1.6.2",
+  "version": "1.7.3",
   "compilerOptions": {
     "target": "es5",
     "module": "commonjs",
diff --git a/typings/es6-object.d.ts b/typings/es6-object.d.ts
index bede479..50cd74e 100644
--- a/typings/es6-object.d.ts
+++ b/typings/es6-object.d.ts
@@ -22,5 +22,3 @@ interface ObjectConstructor {
    */
   setPrototypeOf(o: any, proto: any): any;
 }
-
-declare function require(path:string): any;
```

**Comment by miqmago** [comment]
Done

**Comment by valorkin** [comment]
Awesome! Thanks for PR :)

**Comment by miqmago** [comment]
You are welcome! :)

**Comment by valorkin** [comment]
published, but for some odd reason it is steal 0.46 at https://www.npmjs.com/package/ng2-bootstrap

**Comment by miqmago** [comment]
Hmm... In https://www.npmjs.com/package/ng2-bootstrap it shows 0.48.1. In fact this is weird as in `package.json` the version is 0.48.0. Maybe on your local file you modified it to 0.48.1 and it's not pushed to github yet?

ng2-bootstrap

**Comment by valorkin** [comment]
Yeap, I had to hack a bit to publish this changes

**Pull request merged**
