### PR TITLE
fix(dropdown,rating,typeahead): remove global in order to be usable …

### PR DESCRIPTION
**Pull request by karlhaas**
…with systemjs and aot

### CODE REVIEW

**Comment by valorkin** [comment]
and here https://github.com/valor-software/ng2-bootstrap/pull/1734/files#diff-a4f2d9fe15a93898cef7b2fcb7adc4dbL45
try to replace with Event

and all other places

**Comment by karlhaas** [comment]
why?

**Comment by valorkin** [comment]
If not replace with Event it will throw an error at universal

**Comment by valorkin** [comment]
Thanks

**Comment by karlhaas** [comment]
@valorkin could you please provide a new version?

**Pull request merged**
