### PR TITLE
Popover focus on Mac OS fix

### PR DESCRIPTION
**Pull request by gilsdav**
https://github.com/valor-software/ngx-bootstrap/issues/1795

### CODE REVIEW

**Comment by gilsdav** [comment]
@valorkin  What's wrong ?

**Comment by valorkin** [comment]
why popover needs focus?

**Comment by gilsdav** [comment]
We need to hide it when clicking on other part of page. To be able to have blur event, we need focus before (like all Windows browser does but not some OSX browers). With this correction, it works like base bootstrap component (jquery).

**Comment by SergeyKuryatnick** [comment]
Tested, looks good

**Comment by valorkin** [comment]
Thanks for PR!

**Pull request merged**
