### PR TITLE
feat(datepicker): add hungarian localization

### PR DESCRIPTION
**Pull request by fegyi001**
I added an i18n file for Hungarian localization ('hu'). Also included it in the datepicker demo page.

### CODE REVIEW

**Comment by valorkin** [comment]
@fegyi001 thanks a lot for your contribution! :)
if you will migrate tests too, it will be just awesome

**Comment by JimTudeski** [comment]
This is great, i wanted to ask a Hun localization! ;)

**Review by IlyaSurmay — DISMISSED** [review]

**Comment by valorkin** [comment]
merged with https://github.com/valor-software/ngx-bootstrap/commit/5370c6ad674fd4c80d1e5ea732a3742d3018d6e2

**Comment by valorkin** [comment]
thanks :)

**Pull request closed without merging**
