### PR TITLE
Update to rc.6

### PR DESCRIPTION
**Pull request by otelnov**
- move pipes to ngModel
- stop using  internal API (@angular/core/src/facade/lang)
- Type instead of ConcreteType

### CODE REVIEW

**Comment by Martin-Luft** [comment]
@otelnov thanks for RC6 branch! As mentioned in your RC5 PR:

>  I found 2 other files which should be updated:
> 
> Main README lines 57-59 and 121: deprecated `directives:`
> 
> ng2-bootstrap.ts lines 56-81: all deprecated

Any news when this PR will be merged? I'm asking because your RC5 PR is pending since 13 days and I'm getting impatient and thinking about to switch to https://github.com/ng-bootstrap/ng-bootstrap which supports RC6 already (and it supports RC5 since 22 days) and it looks good to me... I'm asking myself why there must be two Angular 2 bootstrap projects :/ ?

**Comment by Martin-Wegner** [comment]
need commit 7d3cbf93798514a65ba83d62767c49aae7056c96 here

**Comment by PEsteves8** [comment]
I've started using the feat-rc6 branch, but with modals I get a "view.getComputedStyle is not a function" when triggering. Any idea what that is?

Edit: sorry just realizing you're still working on it. I thought I was pointing out something you might have misse.d. Thanks

**Comment by Martin-Luft** [comment]
@PEsteves8 I think the reason is that @otelnov used `type` instead of `window` for the `global` substitutions :(

**Comment by Martin-Luft** [comment]
see PR https://github.com/valor-software/ng2-bootstrap/pull/909

**Pull request merged**
