### PR TITLE
docs(modal): add styling for output for Events, Confirm Window and Modal events example

### LINKED ISSUE #3736: docs(modal): add styling for output for Events, Confirm Window and Modal events example
### Bug description:
- Go to modals demo page
- Choose Bootstrap 4 styles
- Scroll down to Events, Confirm Window or Modal events example
- Fire events, that should be displayed in output
- Look at output syling

outpoutslooksliketext

###Expected result 
Class card card-block card-header should be added inside <pre></pre> tags for all outputs

### PR DESCRIPTION
**Pull request by 5earle**
closes #3736 
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by 5earle** [comment]
Addresses #3736 

add styling for output for Events, Confirm Window and Modal events example

**Review by valorkin — CHANGES_REQUESTED** [review]
Looks good!
except inline styles:
or remove them
or move to component styles

Thanks for your help and time :)

**Comment by 5earle** [comment]
i'm not sure why Travis checks are failing

**Review by valorkin — APPROVED** [review]

**Comment by YevheniiaMazur** [comment]
Tested, looks good

**Comment by valorkin** [comment]
@5earle you have deleted your fork and now I can't fix merge conflict (

**Comment by YevheniiaMazur** [comment]
@valorkin , if I am correct, new PR for these changes is: https://github.com/valor-software/ngx-bootstrap/pull/3976 (without conflicts)

**Pull request closed without merging**
