### PR TITLE
Update radio button directive to work with ReactiveForms

### PR DESCRIPTION
**Pull request by thecontrarycat**
The current implementation of btnRadio only works if there is an [(ngModel)] binding on the element, and does not work correctly with ReactiveForms.

This PR removes the dependency upon ngModel while allowing the btnRadio directive to work in both a ReactiveForms (with formControlName) or TemplateForms (with [(ngModel)] environment.  Furthermore, there is a change to the btnRadio to make it an object so that it can be correctly compared to the model object.

### CODE REVIEW

**Comment by Martin-Luft** [comment]
Ahhhh, we need this for all components:

> pagination.component
> pager.component
> datepicker.component
> datepicker-popup.component
> button-checkbox.directive
> button-radio.directive
> timepicker.component
> rating.component

**Comment by thecontrarycat** [comment]
_Reactive Forms Example_

```
<form [formGroup]="form">
    <div class="form-group">
        <label>Suitable for Vegetarians?</label>
        <div class="btn-group visible-xs-block visible-sm-block visible-md-block visible-lg-block clearfix">
            <label class="btn btn-primary" formControlName="isVegetarian" [value]="form.value.isVegetarian" [btnRadio]="false">No</label>
            <label class="btn btn-primary" formControlName="isVegetarian" [value]="form.value.isVegetarian" [btnRadio]="true">Yes</label>
        </div>
    </div>
</form>
```

**Comment by thecontrarycat** [comment]
_Template Forms Example_

```
<form>
    <div class="form-group">
        <label>Suitable for Vegetarians?</label>
        <div class="btn-group visible-xs-block visible-sm-block visible-md-block visible-lg-block clearfix">
            <label class="btn btn-primary" [(ngModel)]="product.isVegetarian" [value]="product.isVegetarian" [btnRadio]="false">No</label>
            <label class="btn btn-primary" [(ngModel)]="product.isVegetarian" [value]="product.isVegetarian" [btnRadio]="true">Yes</label>
        </div>
    </div>
</form>
```

**Comment by thecontrarycat** [comment]
Looks like the linter is preventing the use of forwardRef, but this seems to be necessary to get the ControlValueAccessor working correctly (see https://github.com/mgechev/angular2-style-guide/issues/56 for other possible uses of forwardRef).

**Comment by bjornharvold** [comment]
+1 one this one

**Comment by Martin-Luft** [comment]
@bjornharvold this issue is closed and already fixed by https://github.com/valor-software/ng2-bootstrap/commit/5d51939092386affc28f2f4bdc488b22d28c1205

**Comment by RolfVeinoeSorensen** [comment]
Can someone show me a html markup and typescript example to use in ReactiveForms?
Is this fix allready in v1.1.16?

**Comment by roscopeeco** [comment]
Can someone show me a html markup and typescript example to use in ReactiveForms?
I am running v1.6.6 and cannot get button groups to work with reactive forms?

https://github.com/ng-bootstrap/ng-bootstrap/pull/1299/files

I have tried using markup from the above link but with no luck.

thanks

**Comment by pantonis** [comment]
@roscopeeco Having the same problem. Did you manage to make it work?

**Comment by roscopeeco** [comment]
No unfortunately not have ended up writing a custom input control

**Pull request closed without merging**
