### PR TITLE
chore(package): update angular2 to version 2.0.0-beta.11

### PR DESCRIPTION
**Pull request by valorkin**
thanks to @mjgp2 and @jdelgadoalfonso

### CODE REVIEW

**Comment by deepakgd** [comment]
Please merge with master and publish ng2-bootstrap for angular2 as soon as possible

**Comment by valorkin** [comment]
two new issues with update to ng2 beta.11:
- dropdown now throws errors when item is selected
- tooltip is not working properly

**Comment by deepakgd** [comment]
oh ok ok. Please fix it as soon as possible. Share error message it will be helpful to solve this issue soon. Because some developers will try to fix it

**Comment by valorkin** [comment]
@deepakgd 
I am afraid 11 version will be later today, if it will be

**Comment by deepakgd** [comment]
Ya in official page of angular2 itself they mentioned this issue. Hope need to wait for beta.12

**Comment by deepakgd** [comment]
Please update to beta 12. @valorkin beta 12 released

**Pull request merged**
