### PR TITLE
fix(demo): remove repetition id in demos

### LINKED ISSUE #3936: fix(demo): remove repetition id in demos
Need to remove all `id` attributes duplicates in demos.

### PR DESCRIPTION
**Pull request by tarusin**
Closes #3936

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

### CODE REVIEW

**Review by IlyaSurmay — DISMISSED** [review]

**Comment by YevheniiaMazur** [comment]
Needs to fix conflicting files

**Review by valorkin — DISMISSED** [review]

**Comment by valorkin** [comment]
@tarusin resolve conflicts

**Comment by YevheniiaMazur** [comment]
Needs to fix conflict before testing

**Comment by tarusin** [comment]
@valorkin @YevheniiaMazur conflicts fixed

**Comment by YevheniiaMazur** [comment]
Got local errors and not actual files locally. Will retest this PR with @tarusin on Monday

**Comment by YevheniiaMazur** [comment]
Tested, looks good

**Pull request merged**
