### PR TITLE
Remove 'z' in slide name

### PR DESCRIPTION
**Pull request by diegochavez**
Looks like is a typo or confusing demo wrong naming on 'slide' called 'slidez'.

### CODE REVIEW

**Comment by valorkin** [comment]
It is not a typo, it was a time when ng2 had a name collision
directive selector - slide
var from ngFor - slide
so it was a real mess there
there are several more things like this
in tabs for example

**Comment by diegochavez** [comment]
I thought was something wrong with that naming. thanks for your hard work @valorkin

**Comment by valorkin** [comment]
I need to cover it with testssssssssss

**Comment by valorkin** [comment]
need to update http://valor-software.com/ng2-charts/ first :(

**Comment by diegochavez** [comment]
Mate I'm looking to use angular2 with charts on a new project, let me know how can help you. 👍

**Comment by valorkin** [comment]
Almost done, updating demos

**Pull request closed without merging**
