### PR TITLE
Angular 2 rc.4 and @angular/forms

### PR DESCRIPTION
**Pull request by jFensch**
Tests are now failing to due to breaking changes in RC.4 testing APIs.  Any help tracking down resolutions would be greatly appreciated.

### CODE REVIEW

**Comment by jFensch** [comment]
@Dinistro @valorkin Could really use some help fixing these tests.  RC.4 breaking changes really made a mess.

**Comment by Dinistro** [comment]
@jFensch I'm sorry, I need to finish something at work and I have finals next week.

**Comment by jFensch** [comment]
Tests have been updated to resolve RC.4 breaking changes.  I'm not sure what's failing in the button tests - updated NgModel provider from @angular/forms should be available in the test context.  Have excluded for now.

Should resolve #627

**Comment by valorkin** [comment]
@otelnov can you please help with updating tests?

**Comment by adrianfaciu** [comment]
What is the status with this pull request ? Can we help in any way ? Kindof a blocker for projects updated to RC.4.

**Comment by valorkin** [comment]
@adrianfaciu @otelnov is working on fixing tests and travis build

**Comment by valorkin** [comment]
Thanks!

**Comment by omargon** [comment]
Hi, when will this fix update be available via NPM? And/or is there another way I can include it on my project? I tried npm install from github via `npm install --save https://github.com/valor-software/ng2-bootstrap.git` but was getting the following error message when building app after it `error TS2307: Cannot find module 'ng2-bootstrap'.`

**Comment by adrianfaciu** [comment]
@omargon You can clone the repo and do a compile (flow.compile). Then you can either use npm install with the folder or do an [npm pack](https://docs.npmjs.com/cli/pack) and install from the tarball.

**Comment by PRR24** [comment]
Is it also expected to solve pagination "ORIGINAL EXCEPTION: No value accessor for ''" issue?
If yes, would be awesome to have the "official" npm package soon.

**Comment by Dinistro** [comment]
@PRR24 Yes it does. 
@valorkin When do you plan to release this?

**Comment by hxlniada** [comment]
@valorkin When do you plan to release this? It's really a blockr

**Comment by superdem** [comment]
Hi @valorkin I updated the ng2-bootstrap to v1.0.19 and also angular RC. 4 but it still gives an error like "No provider for NgModel".
Do you have any suggestion for this ?

**Comment by Dinistro** [comment]
@superdem Did you disable the old forms? 

More infos here: https://github.com/valor-software/ng2-bootstrap/issues/722#issuecomment-231993770

**Comment by superdem** [comment]
@Dinistro Yes,thats the point!
Thank you

**Comment by Slavrix** [comment]
I've got an issue with the datepicker, im getting

```
No provider for NgModel ("StartDatepicker">
[ERROR ->]<datepicker [(ngModel)]='start' datepickerMode='day' minMode='day' maxMode='year' [minDate]='today'
```

Im using ng2-bootstrap:1.0.24
angular2 RC4
ive got the `disableDeprecatedForms(), provideForms()`,
in my bootstrap already

**Pull request merged**
