### PR TITLE
feat(timepicker): remove inline styling, #2496

### PR DESCRIPTION
**Pull request by LimarenkoDenis**
#2496
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

### CODE REVIEW

**Comment by IlyaSurmay** [comment]
Hi!
If you simply remove inline styles from timepicker, it will cause this:
screenshot

So you should replace them with component-scoped styles. Please update your PR.
Thanks for PR!

**Review by IlyaSurmay — CHANGES_REQUESTED** [review]
Inline styles must be replaced with component-scoped styles

**Comment by LimarenkoDenis** [comment]
Sorry for misunderstanding the issue, I updated pull request

**Comment by YevheniiaMazur** [comment]
Tested, looks good

**Comment by valorkin** [comment]
@LimarenkoDenis thanks for the contribution! :)

**Pull request merged**
