### PR TITLE
fix(typeahead): Add formcontrol binding. Fixes #92 (first problem)

### LINKED ISSUE #92: chore(typeahead): inside a form causes issues
Hi,
I've encountered several issues trying to put Typeahead inside a form.
1) ngControl doesn't work (throws a "No provider for NgModel! (Typeahead -> NgModel)" exception)
2) Typeahead inside a form causes submit on enter, form submission should be prevented on enter when the choices are presented (since you just want to select the choice).
3) "autocomplete" should be "off" by default.
4) Also choices should automatically close on blur (This also happens on a non-form typeahead)
5) I think "TAB" should also choose the typeahead choice.

### PR DESCRIPTION
**Pull request by slintes**
all credits go to nrehm: https://github.com/valor-software/ng2-bootstrap/issues/92#issuecomment-198986011

### CODE REVIEW

**Comment by fdu-axiometrics** [comment]
can we merge this to solve the ngControl issue?

**Comment by Jeetah** [comment]
This bug is really annoying since it prevents using ngFormControl with TypeAhead completely. Could someone please merge it?

**Comment by ghost** [comment]
Im facing the same bug here and there is a solution written, merge please?

**Comment by valorkin** [comment]
no worries it will be done

**Comment by Dinistro** [comment]
@slintes There are issues in this fix. Yes, it makes using of `ngControl` possible, but it crashes if you try to use a typeahead without `ngControl`. 

```
Unhandled Promise rejection: Template parse errors:
Cannot instantiate cyclic dependency! NgModel
```

**Comment by marcin992** [comment]
+1

**Comment by valorkin** [comment]
Seems I found a convenient way how to support both of NgModel and NgControl
finishing with docs and datepicker popup and will get here

**Comment by Dinistro** [comment]
New forms and new typeahead implementation.

**Pull request closed without merging**
