### PR TITLE
feat(slider): add new slider component 

### PR DESCRIPTION
**Pull request by jaumard**
Not finished yet but put it here to have feedback ! Be nice it's my first angular component ^^ and I know it's far from perfect. 

Here is the things that need to be done : 
- [x] Basic slider and doc
- [x] Animation when change value
- [x] Range slider
- [x] Tooltips slider
- [x] Selection color support
- [x] Remove all `document` calls 
- [x] Remove all `nativeElement` calls
- [x] Ticks and labels
- [ ] Use CSS preprocessor ? 
- [x] More docs
- [x] Can be use under forms
- [x] Export events (value change, drag start/stop)

If you want to help you're welcome :) I'm basically trying to port [bootstrap-slider](http://seiyria.com/bootstrap-slider/).

If someone could give me example on how remove all `document` and `nativeElement` calls that help me.

Fix: https://github.com/valor-software/ng2-bootstrap/issues/995

### CODE REVIEW

**Comment by jaumard** [comment]
Current preview : 
capture d ecran 2016-09-21 a 22 26 31

**Comment by jaumard** [comment]
I could use some help with with renderers... To set style I can do `this.renderer.setElementStyle(this.minHandle.nativeElement, 'margin-top', '15px');`
But how can I retrieve this value later ?? Because `getElementStyle` doesn't exist... I currently use nativeElement properties to retrieve positions but don't know if it's the right way.

Does the webpack config of ng2-boostrap will build sass if I set it on the component ? 
cc @valorkin

**Comment by jaumard** [comment]
Just see ng2-bootstrap already have tooltips, maybe we can use them...

**Comment by jaumard** [comment]
Hi @valorkin, I think I'm done with this component, I'm open to any suggestion to improve/correct my code. I need you to the last tasks because I don't know how enable SASS on this repo, so for now it's all CSS code.

**Comment by valorkin** [comment]
Usually I am against using sass, because than you need Ruby and all
contributors will have to install it.

**Comment by jaumard** [comment]
I'm on mac so ruby is already installed but I understand ^^ if you want to let CSS or use LESS feel free to do it :) at least LESS will give the possibility to use bootstrap less variables to have consistency in theme for now all is hard coded in CSS

**Comment by jaumard** [comment]
Preview ticks and labels: 
screen shot 2016-09-26 at 08 23 55

**Comment by valorkin** [comment]
Can you dm me in slack? I want to share some ;)

**Comment by valorkin** [comment]
Preview looks very cool!

**Comment by stephanrauh** [comment]
I agree with @valorkin : the static preview looks awesome!

**Comment by daBishMan** [comment]
when is this going to make it out ?

**Pull request merged**
