### PR TITLE
fix(dropdowns): dropdown should close correctly when used in modals (fixes #267, fixes #221)

### LINKED ISSUE #221: bug(demo): dropdown button auto closes
Noticed this on the [docs page](http://valor-software.com/ng2-bootstrap/index-bs4.html#dropdowns) and I did not have the time to test this on my own. (Is it possible to use ng2-bootstrap in plunker?) But when you open the Button Dropdown, it opens and immediately closes.

This occurs on both BS3 & 4 in the docs. The dropdown does work, but only if you use the "Toggle Button Dropdown" button.

### LINKED ISSUE #267: Dropdown not work on angular2-modal
I am using dropdown directive with [angular2-modal](https://github.com/shlomiassaf/angular2-modal)

found the issue that drop-down menu didn't auto close, because modal component will prevent the click event bubbling up.

so, I think the window not appropriated listenser target(in /components/dropdown/dropdown.service.ts)

`window.document.addEventListener('click', this.closeDropdownBind);`

is it possible to change that?

### PR DESCRIPTION
**Pull request by mkjeff**
fixed Dropdown does not work on angular2-modal #267
fixed dropdown button auto closes #221
changed ButtonRadio.btnRadio to be able to hold any object

### CODE REVIEW

**Comment by valorkin** [comment]
I believe it should work for ng2-modal
let me see, what can be done
may be modal component should be changed

**Comment by valorkin** [comment]
@mkjeff ok, now looks even better
1. leave here only dropdown fixes
   buttons will be updated when this will be fixed: https://github.com/angular/angular/issues/7642
2. could you please squash commits while rebasing on top of master? :)
   and name it
   `fix(dropdowns): dropdown should close correctly when used in modals (fixes #267, fixes #221)`

When done, drop a note here, so I will test and merge it ASAP
Thanks in advance :)

**Comment by mkjeff** [comment]
@valorkin had sorted out my commits

**Comment by valorkin** [comment]
Awesome! Merging

**Pull request merged**
