### PR TITLE
fix. disable checkbox buttons

### PR DESCRIPTION
**Pull request by SergeyKuryatnick**
Added check for attribute:Disabled.
Fix https://github.com/valor-software/ng2-bootstrap/issues/1202

### CODE REVIEW

**Comment by valorkin** [comment]
@SergeyKuryatnick fix should be from and to `feat-ng-cli` branch

**Comment by valorkin** [comment]
merged with https://github.com/valor-software/ng2-bootstrap/commit/5e643738c5bcf8998fc8bb22c956141495d06c28

**Comment by Flood** [comment]
Would be nice if this could be added to Radio Buttons as well.

**Comment by sudosandwich3** [comment]
@valorkin any update for fixing this for radio buttons as well?

**Pull request closed without merging**
