### PR TITLE
Fix bootstrap link

### PR DESCRIPTION
**Pull request by peschee**
Change link from pointing to the alpha bootstrap version to the latest website version.

### CODE REVIEW

**Review by IlyaSurmay — APPROVED** [review]

**Comment by peschee** [comment]
@IlyaSurmay The link to the team does not work either. I don't know if that's a link that only works for valor members, but for everyone else, it's a 404.

**Review by valorkin — APPROVED** [review]
Thanks:)

**Comment by valorkin** [comment]
Please edit this file in default dev branch, not master.
Thanks :)

**Comment by peschee** [comment]
Sure, see #3525

**Pull request closed without merging**
