### PR TITLE
fix(tests): "no provider" error when running tests

### PR DESCRIPTION
**Pull request by Igonato**
Fix for #929 

Seems like DI derps in the test environment and not able to resolve providers using the new NgModule system. For tests to pass components need to have providers field.

### CODE REVIEW

**Comment by Martin-Luft** [comment]
@Igonato why is this not needed for `datepicker-popup.component` (I think this component is dead code), `button-checkbox.directive` and `button-radio.directive`? This components and directives also have the ngModel selector binding...? Or are directives not affected?

**Comment by otelnov** [comment]
There is "imports" param in TestBed.configureTestingModule where you can pass FormsModule or whatever you need.

**Comment by Martin-Luft** [comment]
@otelnov this is not working, please see the related issue.

**Comment by Igonato** [comment]
@Martin-Wegner I don't see any datepicker-popup.component what branch are you on? 

As for the others what I did is I imported every ng2-bootstrap module and specified providers field for components that would fail the tests. Test DI doesn't fail for _every_ component nor for _every_ provider, so far it only does so with NgModel and some components. My guess is that some circular dependency needs to happen that can be resolved in the browser but not in testing.

**Comment by valorkin** [comment]
@Igonato I have dropped it completely (datepicker-popup.component ) until it is working properly

**Comment by Igonato** [comment]
@valorkin what was/is wrong with it? 

And what do you think about this PR? Did you review the changes, any comments?

**Comment by valorkin** [comment]
as temporary solution should work, but will have to find more generic solution later

@Igonato thanks for your time! :)

**Pull request merged**
