### PR TITLE
feat(datepicker): added Hebrew locale support for datepicker

### PR DESCRIPTION
**Pull request by msarsha**
Hey,

Added Hebrew locale (#2769).

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [x] added/updated demos.

### CODE REVIEW

**Comment by valorkin** [comment]
@msarsha hey, thanks for the contribution!
but please, remove package-lock

**Comment by valorkin** [comment]
@msarsha maybe you want to add it as an option to demo page?

**Comment by msarsha** [comment]
@valorkin 

[I did add it.](https://github.com/valor-software/ngx-bootstrap/pull/2904/files#diff-e5fa31cae71b33b993a9166ffea3605eR19)

If there are other sections in the demo it should be added to, let me know, I will add it.

**Comment by valorkin** [comment]
@msarsha awesome, thanks. QA will be available on vacation till monday, when she will gave approve we will merge and release it, ok?

**Comment by YevheniiaMazur** [comment]
Tested, looks good. Needs to resolve conflicting file

**Comment by YevheniiaMazur** [comment]
@msarsha , I ment this merge conflict in file demo-datepicker.module.ts: 
conflictingfile

**Comment by valorkin** [comment]
@msarsha hey, thanks a lot for the contribution!
if you can merge tests for locale too, it would be awesome!

**Comment by valorkin** [comment]
thanks again :)

**Pull request merged**
