### PR TITLE
Fix error throw when router view change if tabset directive is included

### PR DESCRIPTION
**Pull request by lanocturne**
When tabset's view is destroyed, for example, the router change. There's an `EXCEPTION: Attempt to use a dehydrated detector.` throw on ng2-beta.6.

Reference Issue: @angular/angular#6786

### CODE REVIEW

**Comment by valorkin** [comment]
Hey, looks good
Can you please squash commits to one and force push to your branch
and apply angular commit naming
commit name: `fix(tabs): ignore destroyed tabs...`
thing is: this should not happen if router will be destroying view content correctly

**Comment by lanocturne** [comment]
Definitely.

Dmitriy Shekhovtsov notifications@github.com於 2016年2月12日 週五，下午10:20寫道：

**Comment by binarious** [comment]
:+1:

**Comment by brian428** [comment]
Any thoughts on when this will be merged?

**Comment by valorkin** [comment]
Right now I am updating ng2-bootstrap up to beta7
so today will be merging testing all PRS
https://github.com/valor-software/ng2-bootstrap/pull/214

**Comment by binarious** [comment]
Still getting errors like `Error: Attempt to use a dehydrated detector: DeliveryShow_2 -> select` on leaving a component with tabs. (ng2 beta7 + n2-bootstrap v1.0.4)

**Comment by binarious** [comment]
Well the fix landed in `v1.0.5`. Now it works.

**Comment by lanocturne** [comment]
Glad to hear that.

binarious notifications@github.com於 2016年2月25日 週四，下午12:25寫道：

**Comment by valorkin** [comment]
@lanocturne I have squashed commits, so you can see release notes now :)
https://github.com/valor-software/ng2-bootstrap/releases

**Pull request closed without merging**
