### PR TITLE
fix(export): all the correct directives are now properly exported

### PR DESCRIPTION
**Pull request by NathanWalker**
Fixed up export file to include all the correct directives plus their dependent directives.
This also provides consistency with the cli `install` tool.

@valorkin Once this is merged, please recompile and post a new version build. Thanks!

### CODE REVIEW

**Comment by valorkin** [comment]
Looks good to me, I can publish but it is useless until I remove dependency on moment
seems typing is still an issue for everyone :)

**Comment by valorkin** [comment]
@NathanWalker published

**Comment by jkuri** [comment]
@valorkin any idea why would the version still be `0.53.0` when installing through `ember-cli` npm script which `angular-cli` uses. I tried installing this with just `npm install ng2-bootstrap` and it installs the latest version. My guess is that `ember-cli` npm script doesn't support versioning like *-beta.2. 
Unfortunately I cannot fix that as `angular-cli` uses `ember-cli` as base. The problem is that version `0.53.0` does not include `bundles/` and correlated script in it. When this version will be out of beta this components will be compatible and I will tried then installing again.

**Comment by valorkin** [comment]
try to install `@latest`?
if not, I will remove beta in version

**Comment by jkuri** [comment]
Tried `ng2-bootstrap@latest` and does not work. Looks like `ember-cli` uses `semver` that does not support prereleases. 
Yes, please remove when you will have time and notify me here.

**Comment by valorkin** [comment]
thing is, semver does support this kind of things http://semver.org/ :)

**Comment by jkuri** [comment]
I know, not sure about version 4.x.x which `ember-cli` uses does. I am guessing.

**Comment by valorkin** [comment]
@jkuri published 1.0.3 you can try now one more time

**Comment by jkuri** [comment]
thanks, some peerDependencies issue now as `angular-cli` still uses angular2-beta.0 because of some jasmine problems. I will have in mind to test this again when angular-clis dependencies will be updated. 
We will make this work as `ng2-bootstrap` is really hardcore and provides many components/directives and it would be really cool to find out working with `angular-cli` as it gives you a nice overview of what the lib provides. 
I double checked the configuration of ng2-bootstrap and everything is configured properly to be compatible with angular-cli, but I cannot be sure until I see it working. Thanks again.

**Comment by valorkin** [comment]
np, keep me updated :)

**Pull request merged**
