### PR TITLE
fix(demo): fixing mobile issues

### PR DESCRIPTION
**Pull request by EvilAlexei**
# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

Closes list of issues:
#3181 - fix(datepicker): datepicker overlap header, when you scroll up page
#3182 - fix(dropdowns): dropdowns overlap header, when you scroll up page
#3183 - fix(popover): popover overlap header, when you scroll up page
#3184 - fix(accordion): custom HTML example for accordion broken on small resolution (bs3)
#3185 - fix(carousel): slide labels cropped on small resolutions
#3186 - fix(datepicker): small field for date output in demo for theme on small resolutions

### CODE REVIEW

**Comment by YevheniiaMazur** [comment]
Needs fix:
1. There are no dropdowns with versions (for desktop, tablet and mobile)
noversiondropdown

2. When user hovers on any title of content, '#' appears near it
symbolneartitle

**Comment by valorkin** [comment]
1 - most probably doesn't relates to this PR
2 - is desired

@EvilAlexei @YevheniiaMazur please get it merge ready on monday

**Comment by YevheniiaMazur** [comment]
Tested, looks good

**Comment by YevheniiaMazur** [comment]
Tested, looks good

**Pull request merged**
