### PR TITLE
feat(compiler-cli): use ngc to generate *.metadata.json

### LINKED ISSUE #933: feat(ng2-cli): add *.metadata.json
**Update** by valorkin:
- npm prepublish should generate metadata

---

When I'm try to launch `ng-xi18n` on rc6 via npm, I have this error:

```
$ ng-xi18n
```

```
Error: Unexpected value 'TypeaheadModule' imported by the module 'LocationModule'
    at /srv/app/node_modules/@angular/compiler/bundles/compiler.umd.js:14118:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/srv/app/node_modules/@angular/compiler/bundles/compiler.umd.js:14103:46)
    at /srv/app/node_modules/@angular/compiler/bundles/compiler.umd.js:12947:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (/srv/app/node_modules/@angular/compiler/bundles/compiler.umd.js:12946:21)
    at Extractor.extract (/srv/app/node_modules/@angular/compiler-cli/src/extract_i18n.js:92:47)
    at extract (/srv/app/node_modules/@angular/compiler-cli/src/extract_i18n.js:16:35)
    at Object.main (/srv/app/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
    at Object.<anonymous> (/srv/app/node_modules/@angular/compiler-cli/src/extract_i18n.js:161:9)
Extraction failed
```

### PR DESCRIPTION
**Pull request by otelnov**
Resolves #933
- update dependencies
- use ngc instead of tsc for compiling 
- make public all private and protected methods to generate ngFactory
- remove the use of es6 templates

### CODE REVIEW

**Comment by otelnov** [comment]
need to remove template literals from components. in progress..

**Comment by otelnov** [comment]
https://github.com/valor-software/ng2-bootstrap/issues/933

**Comment by isaacplmann** [comment]
Is there a timeline for merging this PR?  I'd like to use AoT in my app.

**Comment by valorkin** [comment]
Testing and merging

**Comment by freezy** [comment]
Cool, thanks a lot! Any npm release in sight?

**Comment by valorkin** [comment]
Couple of fixes to merge today

**Comment by freezy** [comment]
You're a champ!

**Pull request merged**
