### PR TITLE
use "window" instead of "Type" for the "global" substitutions

### PR DESCRIPTION
**Pull request by Martin-Luft**
use "window" instead of "Type" for the "global" substitutions

### CODE REVIEW

**Comment by valorkin** [comment]
Please, don't remove event hacks, it is for universal renderer

**Comment by Martin-Luft** [comment]
OK fixed :)

**Comment by valorkin** [comment]
I have digged a bit dipper:
https://github.com/angular/angular/blob/ae75e3640a2d9eb1e897a0771d92b976c5a42c75/modules/@angular/facade/src/browser.ts

it is not so nice in in ng2 + angular universal will get working later,
may be we can drop this hack for now?

**Comment by valorkin** [comment]
@Martin-Wegner fixed, tried to add your authorship but seems failed, sorry :)

**Comment by Martin-Luft** [comment]
OK no problem :)

**Pull request closed without merging**
