### PR TITLE
fix(dropdown): multiple dropdown perf issue

### LINKED ISSUE #2172: fix(dropdown): performance problems with multiple dropdowns
**Description**

We see a big performance problem when using a high number of Dropdowns (e.g. a list of 100 or more elements, each with his own action dropdown). Especially in dev mode the app is getting unresponsible to clicks for seconds.

**Workaround**

Render the dropdown element on mouseenter (simple *ngIf).

**Notes**
Because of the workaround, I think the problem is the high number of global listeners (for closing the dropdown with an outside click). The guys from ng-bootstrap had an similar problem and solved it by register the listeners only when opening a dropdown and remove them on closing.
See https://github.com/ng-bootstrap/ng-bootstrap/issues/900 for the issue or https://github.com/thbt/ng-bootstrap/commit/65778f33871f838341845d7e30d09a43f218ba13 for the fix.

### PR DESCRIPTION
**Pull request by harunurhan**
* Fixes #2172

### CODE REVIEW

**Comment by harunurhan** [comment]
FYI: `npm run test` works and all tests pass locally.

**Review by valorkin — APPROVED** [review]

**Comment by valorkin** [comment]
merged as part of https://github.com/valor-software/ngx-bootstrap/pull/2441
solves perf issue for all dynamic components

**Comment by DLTKPeterEnevoldsen** [comment]
I don't think this solves the mentioned performance problem for dropdowns because there is still an onDocumentClick host binding on the dropdown-toggle directive. This listener will be always be attached and when we have many (1000s) of dropdown-toggles the performance will still be slow.

**Comment by valorkin** [comment]
Yeah, we could not remove it, because of inline mode.
But there are one PR to remove this listener

**Comment by DLTKPeterEnevoldsen** [comment]
Thank you for the quick reply. Will it be possible to include the PR in the next release.

**Comment by valorkin** [comment]
Not sure, dev who was working on it, is on vacation this week

**Comment by DLTKPeterEnevoldsen** [comment]
No problem. Thank you very much for the update.

**Comment by harunurhan** [comment]
@PeterEnevoldsen well, this reduces number of global click listeners for dropdowns to a single one, which the issue mentioned, that's why I linked the issue but didn't look at it closely, sorry about that! 😟

**Pull request closed without merging**
