### PR TITLE
Add Japanese bs-moment #prepare() method

### PR DESCRIPTION
**Pull request by Neos21**
I made Japanese #prepare() method of bs-moment.

### CODE REVIEW

**Comment by valorkin** [comment]
@Neos21GitHub awesome, thanks!
can you cover it with tests, please?
can you merge this one?
 https://github.com/moment/moment/blob/develop/src/test/locale/ja.js

**Review by valorkin — APPROVED** [review]

**Comment by YevheniiaMazur** [comment]
Tested, looks good

**Comment by Neos21** [comment]
Thank you very much!
This is my first pull request in my life. I'm glad to be merged. :)

**Comment by valorkin** [comment]
Hohoho, my congratulations! Welcome to open source :)

**Pull request merged**
