### PR TITLE
fix(datepicker): using icons instead of innerHTML chevrons to fix iss…

### PR DESCRIPTION
**Pull request by artdias90**
…ue with webworkers

### CODE REVIEW

**Comment by artdias90** [comment]
@valorkin any chance you can take a look at this soon? it's a small one and would help me out a lot so I don't need to use my fork any longer

**Comment by valorkin** [comment]
problem with this is:
```
const TEMPLATE_OPTIONS: any = {
  'bs4': {
    ARROW_LEFT: '&lt;',
    ARROW_RIGHT: '&gt;'
  },
  'bs3': {
    ARROW_LEFT: `
    <i class="glyphicon glyphicon-chevron-left"></i>
    `,
    ARROW_RIGHT: `
    <i class="glyphicon glyphicon-chevron-right"></i>
    `
  }
};
```
so this PR will break bs4 view,
you can add `*ngIf=isBs4` and add corresponding elements

**Comment by artdias90** [comment]
I removed the template interface since its unused now

**Comment by artdias90** [comment]
remove this TEMPLATE_OPTIONS object since we dont use anymore. @valorkin lmk

**Pull request merged**
