### PR TITLE
feat(bundle): to UMD format

### PR DESCRIPTION
**Pull request by lifaon74**
Quick fix from https://github.com/valor-software/ng2-bootstrap/issues/1093

### CODE REVIEW

**Comment by lifaon74** [comment]
I inline source maps because I let developpers to minimize by themself files (and removing comments). It avoids to have too many files. You can change it as your conveniance.

**Comment by valorkin** [comment]
Without this key mouse events, universal is not working :)

**Comment by valorkin** [comment]
can you leave here only .npmignore and make.js files?
and revert all other changes?

**Comment by lifaon74** [comment]
Done

**Comment by valorkin** [comment]
Please check that AoT works fine,
I will play with this one :)
Thanks for quick reaction

**Comment by lifaon74** [comment]
My bad, i forgot to rollback some files

**Comment by valorkin** [comment]
ok, thing is
If I am planning to roll out this one
everybody will have to, replace 
`import 'ng2-bootstrap\ng2-bootstrap'` to `import 'ng2-bootstrap'`
what is actually an artifact from ng2 alfas

**Comment by valorkin** [comment]
ok, testing with system.js and ng-cli (webpack)

**Comment by valorkin** [comment]
ng-cli: normal and AoT versions both imports working fine ;)

**Comment by valorkin** [comment]
released as @beta,
check plunker and angular2-quickstart

**Pull request closed without merging**
