### PR TITLE
chore(docs): Update set bootstrap version guide and docs

### PR DESCRIPTION
**Pull request by envil**
# PR Checklist
 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

### CODE REVIEW

**Comment by envil** [comment]
Issue #4186

**Review by valorkin — DISMISSED** [review]

**Comment by valorkin** [comment]
@envil Thanks for PR!

**Review by valorkin — DISMISSED** [review]

**Comment by valorkin** [comment]
thanks one more time :)

**Comment by valorkin** [comment]
sorry for a delay, was busy organizing https://ngtalks.io/

**Pull request merged**
