### PR TITLE
feat(accordion): add key navigation to accordion

### LINKED ISSUE #3992: refactor(accordion): add key navigation to accordion
1. Add an option to switch to accodion component using Tab button
2. Add an option to open and close accordion using Enter and Space button

### PR DESCRIPTION
**Pull request by ghost**
1. I've changed html template in accordion component to add option:

- [x] switch between accordion titles by pressing tab button
joxi_screenshot_1521640908758
- [x] open/close accordion's content by Enter and Space button:
when accordion title is focused, press  Enter or Space button - and accordion's content open or close.
joxi_screenshot_1521641160089

You can try it in accordion (component) section in the demo.

closes #3992

### CODE REVIEW

**Review by IlyaSurmay — DISMISSED** [review]

**Comment by YevheniiaMazur** [comment]
Please, add link to issue, due to what this PR was created.

**Comment by ghost** [comment]
@YevheniiaMazur fixed

**Comment by YevheniiaMazur** [comment]
Not clear: do you mean open accordion with Enter key and close it by Space key?

**Comment by ghost** [comment]
@YevheniiaMazur I've change description

**Comment by YevheniiaMazur** [comment]
Tested, looks good

**Review by valorkin — APPROVED** [review]

**Pull request merged**
