### PR TITLE
feat(positioning): auto option for positioning

### PR DESCRIPTION
**Pull request by vfcosta**
This pull request is a proposal to solve #1111.

### CODE REVIEW

**Comment by valorkin** [comment]
tried different scenarios and there some positioning issues
@IlyaSurmay knew more details
we will get to this later a bit

**Comment by evandrojr** [comment]
+1 Very nice feature, hope it get fixed and merged soon!

@IlyaSurmay please, give us some sample code of the positioning issue happening. Maybe I can help.

Thanks

**Comment by leandronunes** [comment]
+1

**Comment by leandronunes** [comment]
@valorkin @IlyaSurmay could you please merge this code?

**Comment by Valery-vs** [comment]
+1

**Comment by evandrojr** [comment]
+1

**Comment by cannontechnology** [comment]
+1 ETA on when this will be merged?

**Review by evandrojr — COMMENTED** [review]
Everything fine to me!

**Review by EvilAlexei — APPROVED** [review]
All is fine :)

**Comment by valorkin** [comment]
@vfcosta thanks for PR!

**Pull request merged**
