### PR TITLE
Instructions for BS4 and ng-cli

### PR DESCRIPTION
**Pull request by DouglasWebster**
Instructions on how to set up ng2-bootstrap for Bootstrap 4 based on an angular-cli generated project.  This should hopefully remove the confusion a few people have over certain components not working when using Bootstrap 4.

### CODE REVIEW

**Comment by valorkin** [comment]
Looks great, add a links to landing and readme.md files so it can be found

Huge work, thank you!

**Comment by DouglasWebster** [comment]
What do you mean by adding links to landing?  Can see where to add links in the .md files but cannot find a landing file.

**Comment by valorkin** [comment]
It am generating landing from MD files

**Comment by DouglasWebster** [comment]
Added links to the new instructions to readme.md and getting-started.md

**Comment by valorkin** [comment]
Awesome, thank you!

**Pull request merged**
