### PR TITLE
feat(typeahead): scroll feature for typeahead

### PR DESCRIPTION
**Pull request by arins**
Implemented scroll for typeahead #1168

### CODE REVIEW

**Comment by arins** [comment]
@valorkin I made a new pull request with your latest code.

**Comment by valorkin** [comment]
Awesome, thanks. I will still need to understand it better before merge
DM me in slack I will share some details about typeahead plans

**Comment by valorkin** [comment]
I am planning spent next week full-time for ng2-bootstrap

**Comment by vsm-zz** [comment]
@valorkin We are waiting for the update on fix for typeahead for not showing more than 20 records by default when no search was performed. Please let us know when this will be available

**Comment by aleor** [comment]
Hello, are there any news on when this feature can be merged?..

**Comment by vikkivikrant** [comment]
@valorkin @arins Hi, any update on this, when this feature will be added?? It will be big win if we can add it soon. Thanks in advance.

**Comment by valorkin** [comment]
This/next we are finishing modal component loader. And then going to work on Typeahead and datepicker fixes/rewrite

**Comment by vikkivikrant** [comment]
Thanks @valorkin  & @arins : Are you also adding feature where user can hold down/up arrow keys and it will keep moving to next/previous items. This will be very useful when you have too many items to look into.


Adding below code will do it :

Method to add it : 
@HostListener('keydown', ['$event'])
public onKeydown(e: any):

Add below code into above method :

      // down
      while (e.keyCode === 40) {
        this._container.nextActiveMatch();
        return;
      }

      // up
      while (e.keyCode === 38) {
        this._container.prevActiveMatch();
        return;
      }

**Comment by vikkivikrant** [comment]
@valorkin @arins  Any updates on this will be greatly appreciated.

**Comment by SergeyKuryatnick** [comment]
Need to solve conflicts

**Comment by WhoStoleMyToast** [comment]
@SergeyKuryatnick @valorkin @IlyaSurmay Any updates on this?

**Comment by NickManojlovic** [comment]
@SergeyKuryatnick @valorkin @IlyaSurmay any updates on the scrollable feature? I am in a real need of this functionality. I tried to modify CSS to show the dropdown but I am experiencing some IE11 issues when the scroll button is clicked the dropdown closes.  Much appreciate it.

**Comment by IlyaSurmay** [comment]
Huge thanks for PR! 
Due to the fact that lib structure has been changed a lot since this PR was created, we decided to take it as a draft and replace it with #2821.

**Comment by IlyaSurmay** [comment]
Huge thanks for PR!
Due to the fact that the lib structure has been changed a lot since this PR was created we decided to use it as a draft for #2821.

**Comment by IlyaSurmay** [comment]
Huge thanks for PR!
Due to the fact that lib structure has been changed a lot since this PR was created, we decided to take it as a draft and replace it with #2821.

**Pull request closed without merging**
