### PR TITLE
fixed #1629 duplicate tab issue

### LINKED ISSUE #1629: dynamic tabs are duplicated if component updates items
Hi im having problems creating a dynamic tabs control that is able to update.

i have a repro repository here:

https://github.com/JanEggers/Repro/

and the component is

/master/src/Repro/ClientApp/app/home/home.component.ts

the issue is every time i update the array of items the tabs are bound to the dynamic tabs are duplicated.

when i look at it with augury the tabs property of the tabsetcomponent has the wrong count.
the number of tab elements seems correct but the number of spans in the ul is too high.

### PR DESCRIPTION
**Pull request by JanEggers**
this is a possible fix for #1629

### CODE REVIEW

**Comment by Flood** [comment]
@JanEggers Can you fix the broken test so this can be merged?

**Comment by JanEggers** [comment]
@valorkin can you please assist? I cant figure out why the test cases i added are not working.

Before adding the new test the pr was fine just a little less coverage.

**Comment by valorkin** [comment]
Sure, I will take a look

**Comment by JanEggers** [comment]
@IlyaSurmay : thx for fixing my pr @valorkin: can u please review and merge

**Comment by valorkin** [comment]
@SergeyKuryatnick can you tests it so we can merge

**Comment by valorkin** [comment]
Thanks for PR!

**Pull request merged**
