### PR TITLE
feat(dropdown): add option to let event propagate on toggle

### PR DESCRIPTION
**Pull request by H--o-l**
Issue valor-software/ngx-bootstrap#1217 was fixed but re-introduce
recently in development branch (commit 04cab1eb6f42ad7a6456c34a0ec54f9bd37fd83a).

Let's add an option to authorize propagation of click event on toggle
for users that need it.

### CODE REVIEW

**Comment by valorkin** [comment]
@H--o-l question is: if add `(click)="return false;"` should it do the same?

**Comment by valorkin** [comment]
@H--o-l as far as I remember I was fighting with document click closing just opened dropdown :)

**Comment by H--o-l** [comment]
@valorkin ok, not sure what you mean but I'm glad to do some tests if you have ideas.

For now I tried:
`<button dropdownToggle (click)="false">` which doesn't work and `<button dropdownToggle (click)="return false">` which doesn't compile.

Before submitting the PR I also tried to remove the `event.stopPropagation()` in dropdown-toggle directive and it was ok for my app.

Do you have other suggestions ? Or did I missed something ?

**Comment by valorkin** [comment]
what if completely remove `event.stopPropagation()` from drop down toggle
but `(click)="$event.stopPropagation()"` should work in the same way
need to try this
cc #2800

**Comment by H--o-l** [comment]
@valorkin just to add water under the bridge, you did say, in this discussion valor-software/ngx-bootstrap#1217, that twitter bootstrap stop the click event.
I don't know twitter bootstrap myself but it's seems a legitimate reason to put `event.stopPropagation()` where you did, but we need the option to desactivate it :-)

**Comment by valorkin** [comment]
https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L205-L209

**Comment by valorkin** [comment]
yep they use it a lot

**Comment by valorkin** [comment]
@H--o-l thanks again :)
we will see where it will take us

**Comment by H--o-l** [comment]
@valorkin thanks to you !

**Comment by valorkin** [comment]
My hope to release it today

**Pull request merged**
