### PR TITLE
Ability to control animation on progress bar

### PR DESCRIPTION
**Pull request by Confusedfish**
Hi @valorkin, I had need to control the animation of the Progress Bar, I could have just been doing things incorrectly so feel free to shoot me down but otherwise I have added the "active" class to the <bar> element when the ProgressBar.Animate == true

### CODE REVIEW

**Comment by Confusedfish** [comment]
Note, this now also relates to issues #493 & #825

**Comment by valorkin** [comment]
Can you allow me to modify your branch?
Here should be a checkbox (in PR)

**Comment by Confusedfish** [comment]
That appears to be checked already `Allow edits from maintainers`?

**Comment by valorkin** [comment]
Yeap, awesome

**Comment by valorkin** [comment]
https://github.com/kentcdodds/cross-env
Set doesn't work on Linux

**Comment by Confusedfish** [comment]
Tested compiling on Windows and Linux, seems to be working to me now using cross-env

**Comment by Confusedfish** [comment]
Going to close this PR since it all got a bit confused between the changes for Windows compile & the active state on the ProgressBar. I will make another PR in a branch once I can get some free time.

**Comment by valorkin** [comment]
Thanks! :)

**Pull request closed without merging**
