### PR TITLE
Update template to ng-template (angular@4.0.0-rc3)

### PR DESCRIPTION
**Pull request by nikolasleblanc**
Couldn't get protractor tests to run, so can't guarantee they still work. Would be worth verifying. But this will get ng2-bootstrap to angular@4.0.0-rc.3 and replaces all `<template>`'s with `<ng-template>`'s.

### CODE REVIEW

**Comment by nikolasleblanc** [comment]
Can't really make sense of these codecov warnings, since their links mention "missing base reports". Happy to clean them up if you can point me in a direction.

**Comment by Martin-Luft** [comment]
This PR will not work. @valorkin is working on that: https://github.com/valor-software/ng2-bootstrap/issues/1692

**Comment by nikolasleblanc** [comment]
Why's that @Martin-Wegner? Seemed to pass all the tests on Travis.

**Comment by Martin-Luft** [comment]
@nikolasleblanc 

> Couldn't get protractor tests to run, so can't guarantee they still work.

:P

I don't know if it would work but @valorkin has a lot of trouble with ng4 :(

**Comment by nikolasleblanc** [comment]
Well, yeah, but to be honest I couldn't get much to run at all until I figured out what global dependencies I needed to run tests or a build. The fact protractor wouldn't work on my end didn't tell me much given the circumstances.

Travis running protractor against sauce labs was reassurance that we were good.

What are the angular 4 issues you are running into? Been in those weeds awhile now, I could help out if you needed.

**Comment by Martin-Luft** [comment]
@valorkin get in touch with @nikolasleblanc please :)

@nikolasleblanc you can find @valorkin here: https://ngx-home.slack.com/messages/@valorkin/

**Comment by nikolasleblanc** [comment]
> Don't have an @valor-software.com email address? 

Can't register. :(

**Comment by Martin-Luft** [comment]
@nikolasleblanc https://ngx-slack.herokuapp.com/

**Comment by valorkin** [comment]
ups, sorry did not saw this
you can try ng v4 version with `npm i -S ng2-bootstrap@beta`

**Comment by valorkin** [comment]
but thanks for your time and efforts!

**Comment by nikolasleblanc** [comment]
Cool thanks @valorkin

**Pull request closed without merging**
