### PR TITLE
tooltip with html support

### PR DESCRIPTION
**Pull request by erashu212**
Hi @valorkin ,

This is fix for #474 .

After merging this PR, we need to update the demo site.

`<a href="#" tooltip [tooltipHtml]="dynamicTooltip">I am tooltip</a>`

Thanks

### CODE REVIEW

**Comment by valorkin** [comment]
Looks simple and good enough
Can you please update doc about it?

**Comment by brulejr** [comment]
This change did not make the v1.0.17 release, correct? If this is the case, when is the next release planned?

**Comment by vmironovs** [comment]
+1 can you please merge this ?

**Comment by gocemitevski** [comment]
Any plans for supporting HTML in tooltips, anytime soon?

**Comment by jamiec1234** [comment]
Agreed, this would be super useful.

**Pull request closed without merging**
